#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc.
"

if ! [ $LEGATO_ROOT ]; then echo "Run bin/legs first" >&2; exit 1; fi
. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="creates a toolkit enabling Legato software development"

help_usage=(
""
)

help_long_description=(
"Once Legato tools have been built, this script stages files and produces a tarball."
)

CheckForHelp $@

# Default SDK prefix
RELEASE_DIR=$LEGATO_ROOT/releases
LEGATO_VERSION=$(cat $LEGATO_ROOT/version)
SDK_PREFIX=${SDK_PREFIX:-""}
STAGING_DIR="$LEGATO_ROOT/build/tools/staging"
ARCH=$(uname -m)
TOOLS_ARCH=${TOOLS_ARCH:-$ARCH}

if [ -n "$SDK_PREFIX" ]; then
    STAGING_DIR="$STAGING_DIR/$SDK_PREFIX"
fi

set -xe

echo "Cleaning ..."
rm -rf ${STAGING_DIR}

echo "Staging ..."
install -d ${STAGING_DIR}/bin/
install -d ${STAGING_DIR}/lib/

# mk tools
install ./bin/mk* ${STAGING_DIR}/bin/
ln -sf mk ${STAGING_DIR}/bin/mkcomp
ln -sf mk ${STAGING_DIR}/bin/mkexe
ln -sf mk ${STAGING_DIR}/bin/mkapp
ln -sf mk ${STAGING_DIR}/bin/mksys
install build/tools/lib/libdefTools.so ${STAGING_DIR}/lib/

# scripts
for script in $(ls -1 framework/tools/scripts); do
    install framework/tools/scripts/$script ${STAGING_DIR}/bin/
done

# ifgen
cd framework/tools/ifgen
for tool in $(find -type f -and -not -name "*.pyc" | sed 's/^\.\///' | grep -v "langSample"); do
    install -D $tool ${STAGING_DIR}/bin/$tool
done

# IMA
cd $LEGATO_ROOT
install 3rdParty/ima-support-tools/ima-sign.sh ${STAGING_DIR}/bin/
install 3rdParty/ima-support-tools/ima-gen-keys.sh ${STAGING_DIR}/bin/

echo "Releasing ..."
mkdir -p $RELEASE_DIR
cd $STAGING_DIR
tar jcvf $RELEASE_DIR/legato-tools-${TOOLS_ARCH}-${LEGATO_VERSION}.tar.bz2 *
ln -sf legato-tools-${TOOLS_ARCH}-${LEGATO_VERSION}.tar.bz2 $RELEASE_DIR/legato-tools-${TOOLS_ARCH}.tar.bz2
