#!/bin/bash

# Search in known locations for a cross-build tool chain.
# The first argument is the target type (ar7, wp85, etc.)
function PrintHelp()
{
cat << ENDHELP
NAME
        $(basename $0) - search for an installed cross-build toolchain for a given type of target.

SYNOPSIS
        $(basename $0) TARGET [dir or prefix]

DESCRIPTION
        Will output the toolchain directory directory (or prefix) to stdout and exit with code 0 on success.

        Prints an error message to stderr and exits with a non-zero exit code on error.
ENDHELP
}

HOST_ARCH=$(uname -m)
TARGET=$1
CMD=${2:-dir}

# Select the appropriate list of toolchain directories to search, in order of preference
# (most preferred first) based on the target name given.
case "$TARGET" in
ar7 | ar86)
    TOOLCHAIN_DIRS=(
        /opt/swi/y16-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        /opt/swi/y14-ext/tmp/sysroots/$HOST_ARCH-linux/usr/bin/armv7a-vfp-neon-poky-linux-gnueabi
        )
    ;;
wp85 | wp750x)
    TOOLCHAIN_DIRS=(
        /opt/swi/y17-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        )
    ;;
ar758x)
    TOOLCHAIN_DIRS=(
        /opt/swi/y17-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        )
    ;;
ar759x)
    TOOLCHAIN_DIRS=(
        /opt/swi/y17-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        )
    ;;
raspi | virt_arm)
    TOOLCHAIN_DIRS=(
        /tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin
        /opt/swi/y17/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        /opt/swi/y17-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        /opt/swi/y16/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        /opt/swi/y16-ext/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
        )
    ;;
virt_x86)
    TOOLCHAIN_DIRS=(
        /opt/poky/1.6.1/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/i586-poky-linux
        /opt/poky/y16/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/i586-poky-linux
        /opt/poky/y17/sysroots/$HOST_ARCH-pokysdk-linux/usr/bin/i586-poky-linux
        )
    ;;
help | --help | -h)
    PrintHelp
    exit 0
    ;;
*)
    echo "****ERROR: Unrecognized target type '$1'." >&2
    exit 1
    ;;

esac

check_toolchain_dir() {
    dir=$1

    COMPILER_EXEC=gcc
    if [[ "$USE_CLANG" == "1" ]]; then
        COMPILER_EXEC=clang
    fi

    for entry in $(find $dir -name "*$COMPILER_EXEC" 2>/dev/null); do
        if [[ "$CMD" == "dir" ]]; then
            echo "$dir"
        elif [[ "$CMD" == "prefix" ]]; then
            echo $(basename $entry | sed 's/'$COMPILER_EXEC'$//')
        else
            echo "Unknown option $CMD"
            exit 1
        fi

        return 0
    done

    return 1
}

TOOLCHAIN_DIR_ENV="${TARGET^^}_TOOLCHAIN_DIR"
TOOLCHAIN_DIR="${!TOOLCHAIN_DIR_ENV}"
if [ -n "$TOOLCHAIN_DIR" ]
then
    if ! check_toolchain_dir $TOOLCHAIN_DIR; then
        echo "Toolchain specified for target '$1' is invalid." >&2
        exit 1
    fi

    exit 0
fi

# Go down the list until we find one that exists.
for dir in ${TOOLCHAIN_DIRS[*]}
do
    if check_toolchain_dir $dir; then
        exit 0
    fi
done

echo "No toolchain found for target '$1'." >&2
exit 1

