#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"
#
# Host-based wrapper around target-based fwupdate tool
#
if ! [ $LEGATO_ROOT ]; then echo "Run bin/legs first" >&2; exit 1; fi
. "${LEGATO_ROOT}/framework/tools/scripts/shlib"

help_short_desc="download or query modem firmware"

help_usage=(
"help"
"download FILE [TARGET_IP]"
"query [TARGET_IP]"
)

help_long_description=(
"$commandName help"
"  - Print this help message and exit"
""
"$commandName download FILE [TARGET_IP]"
"  - Download the given CWE file."
"    After a successful download, the modem will reset."
""
"$commandName query [TARGET_IP]"
"  - Query the current firmware version. This includes the modem firmware version, the"
"    bootloader version, and the linux kernel version."
"    This can be used after a download and modem reset, to confirm the firmware version."
)

CheckForHelp $@

COMMAND=$1

if [ "$COMMAND" = "query" ]
then
    SetTargetIP $2
    SshToTarget "/usr/local/bin/fwupdate query"
    exit 0
fi

if [ "$COMMAND" = "download" ]
then
    FILE=$2
    if ! [ -f "$FILE" ]
    then
        ExitWithError "File '$FILE' does not exist or is not specified"
    fi

    SetTargetIP $3

    cat "$FILE" | SshToTarget "/usr/local/bin/fwupdate download -"
    exit 0
fi


ExitWithError "Command '$COMMAND' unknown."
