#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

if ! [ $LEGATO_ROOT ]; then echo "Run bin/legs first" >&2; exit 1; fi
. "${LEGATO_ROOT}/framework/tools/scripts/shlib"

help_short_desc="install app on target"

help_usage=(
"APP_FILE [TARGET_IP]"
)

help_long_description=(
"Install the given app on the target at TARGET_IP"
"APP_FILE is the file containing theapplication to be installed."
"E.g., 'myApp.ar7'."
)

CheckForHelp $@
APP_FILE=$1

# Check that the first argument exists and is a file.
if ! [ -f "$APP_FILE" ]
then
    ExitWithError "First argument should be an application file."
fi

# Check that the second argument is provided and can be pinged.
SetTargetIP $2

# Feed the application file into tar xf running in the application install directory.
APP_NAME=$(basename "$APP_FILE" | sed 's/\.[^.]*$//')
echo "Installing application '$APP_NAME' from file '$APP_FILE'."
cat $APP_FILE | SshToTarget "/usr/local/bin/app install '$APP_NAME'"
