#!/bin/bash

# This script installs the Legato framework in /usr/local on a target device using SSH.
# It will also install the startup scripts if they are not present or they are different
# from the startup scripts in the $LEGATO_ROOT dir on host.

# Exit codes
# 0 - Success
# 1 - General error
# 42 - Startup files were updated and the target must be rebooted before trying to run this script again.


function PrintUsage()
{
    echo "USAGE: $(basename $0) BUILD_DIR [DEST_IP]"
    echo
    echo "  where, BUILD_DIR = the directory in which the target's built Legato files can be found."
    echo "                     E.g., 'build/ar7'."
    echo
    echo "         DEST_IP = the IP address of the target device."
    echo
    echo "If DEST_IP is not provided on the command-line, $(basename 0) will try to use the"
    echo "contents of the DEST_IP environment variable."
    echo
}

BUILD_DIR=$1
TARGET_IP=$2

# Check if they are asking for help.
if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
then
    PrintUsage
    exit 0
fi

# Check that the first argument exists and is a directory.
# If not, try sticking "build/" on the front and see if that's a directory.
if ! [ -d "$BUILD_DIR" ]
then
    BUILD_DIR_TRY2="build/$BUILD_DIR"
    if ! [ -d "$BUILD_DIR_TRY2" ]
    then
        echo "***ERROR: First argument should be a directory."
        echo "Directory '$BUILD_DIR' not found."
        echo "Perhaps it needs to be built?"
        echo
        PrintUsage
        exit 1
    else
        BUILD_DIR="$BUILD_DIR_TRY2"
    fi
fi

# Must make sure we are using install scripts that match the version of the framework that we
# are installing, so override LEGATO_ROOT based on the BUILD_DIR
LEGATO_ROOT="$BUILD_DIR/../.."
if ! [ -f "$LEGATO_ROOT/version" ] || ! [ -f "$LEGATO_ROOT/README.md" ]
then
    echo "***ERROR: '$LEGATO_ROOT' does not appear to be a Legato framework directory."
    echo
    PrintUsage
    exit 1
fi

# If the second argument is provided, use that as the target device IP address.
# Otherwise, look for a DEST_IP environment variable.
if ! [ $TARGET_IP ]
then
    if ! [ $DEST_IP ]
    then
        echo "***ERROR: Destination IP address not available."
        PrintUsage
        exit 1
    fi

    TARGET_IP=$DEST_IP
fi

TAR_FILE="$BUILD_DIR/legato-runtime.tar"

if ! [ -f "$TAR_FILE" ]
then
    echo "***ERROR: Runtime tarball '$TAR_FILE' not found."
    echo "Are you sure '$BUILD_DIR' is a target-specific Legato build directory and"
    echo "the build has completed successfully?"
    echo
    PrintUsage
    exit 1
fi

echo "Installing Legato framework from: $BUILD_DIR"

# Copy the legato script onto the target.
scp -o ConnectTimeout=1 $LEGATO_ROOT/targetFiles/shared/bin/legato root@$TARGET_IP:/tmp/legatoInstaller &&

# Start the legato script on target and stream the tarball of the target device's staging to it.
cat "$TAR_FILE" |
ssh -o ConnectTimeout=1 root@$TARGET_IP '
    chmod u+x /tmp/legatoInstaller
    /tmp/legatoInstaller install
    '
