#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="install app on target"

help_usage=(
"APP_FILE [TARGET_IP]"
)

help_long_description=(
"Install the given app on the target at TARGET_IP"
"APP_FILE is the file containing theapplication to be installed."
"E.g., 'myApp.ar7'."
)

CheckForHelp $@
APP_FILE=$1

# Check that the first argument exists and is a file.
if ! [ -f "$APP_FILE" ]
then
    ExitWithError "First argument should be an application file."
fi

# Check that the second argument is provided and can be pinged.
SetTargetIP $2

# Compute the APP_NAME and TARGET.
APP_BUNDLE_FILE_NAME=$(basename "$APP_FILE")
APP_NAME=$(echo "$APP_BUNDLE_FILE_NAME" | sed 's/\.[^.]*$//')
TARGET=$(echo "$APP_BUNDLE_FILE_NAME" | sed "s/^$APP_NAME\.//")

# Pack the app bundle file into an update pack and pipe that to the on-target "update" program
# through ssh.
echo "Installing app '$APP_NAME' from file '$APP_FILE' onto device at address '$TARGET_IP'."
update-pack $TARGET -ai $APP_FILE -o - | SshToTarget "/usr/local/bin/update"
