#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="install system on target"

help_usage=(
"SYSTEM_FILE [TARGET_IP]"
)

help_long_description=(
"Install the given system on the target at TARGET_IP"
"SYSTEM_FILE is the file containing the system(collection of apps) to be installed."
"E.g., 'mySys.ar7_sys'."
)

CheckForHelp $@
SYSTEM_FILE=$1

# Check that the first argument exists and is a file.
if ! [ -f "$SYSTEM_FILE" ]
then
    ExitWithError "First argument should be a system file."
fi

# Check that the second argument is provided and can be pinged.
SetTargetIP $2

# Feed the system installation file to system installation tool at target.
echo "Installing system from file '$SYSTEM_FILE'."
cat $SYSTEM_FILE | SshToTarget "/usr/local/bin/sys install"
