#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

if ! [ $LEGATO_ROOT ]; then echo "Run bin/legs first" >&2; exit 1; fi
. "${LEGATO_ROOT}/framework/tools/scripts/shlib"

help_short_desc="list apps on target"

help_usage=(
"[TARGET_IP]"
)

help_long_description=(
"List all apps on the target at TARGET_IP"
)

CheckForHelp $@

SetTargetIP $1

# List the contents of the application install directory.
SshToTarget "/usr/local/bin/app list"

