#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="create Legato image partition"

help_usage=(
"[OPTIONS]"
)

help_long_description=(
"Generate a partition for a Legato target."
""
"Options:"
" - -t [TARGET]: target the image should be generated for (ar7, ...)"
" - -d [STAGING_DIR]: staging directory for that platform"
" - -o [OUTPUT_DIR]: output directory where the image will be stored"
""
"For ar7/ar86/wp85/wp750x/wp76xx targets:"
""
"   This creates a partition that you can use with fwupdate or airvantage"
"   to update the legato within your target."
)

CheckForHelp $@

CheckRet() {
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        echo "Exit Code $RETVAL"
        exit $RETVAL
    fi
}

while getopts ":t:o:d:v:" arg
do
    echo "$OPTARG == $(readlink -f $OPTARG)"

    case $arg in
    t)
        TARGET=$OPTARG
        ;;
    d)
        STAGING_DIR=$(readlink -f $OPTARG)
        ;;
    o)
        OUTPUT_DIR=$(readlink -f $OPTARG)
        ;;
    v)
        VERSION=$OPTARG
        ;;
    ?)
        echo "$0: invalid option -$OPTARG"
        usage_and_exit 1
        ;;
    esac
done

if [ -z "$VERSION" ]; then
    if [ -z "$LEGATO_ROOT" ]; then
        echo "Unable to determine version"
        exit 1
    fi

    VERSION="$(cat $LEGATO_ROOT/version)"
    if [ -e "$LEGATO_ROOT/.git" ]; then
        VERSION="$VERSION $(git rev-parse --short HEAD)"
    fi
    VERSION="$VERSION $(hostname) $(date +'%Y/%m/%d %H:%M:%S')"
fi

if [ -z "$TARGET" ]; then
    echo "Target (-t) not set"
    exit 1
fi

FindToolchain

CheckFakerootVersion() {
    FAKEROOT_BIN=$1
    FAKEROOT_VERSION=$($FAKEROOT_BIN --version | awk '{print $3}')
    REQUIRED_VERSION="1.20.2"
    [ "$REQUIRED_VERSION" = "$(echo -e "$REQUIRED_VERSION\n$FAKEROOT_VERSION" | sort -V | head -1)" ]
}

# Need to appear as root to prepare images
if [ $(id -u) -ne 0 ]; then
    FindTool "fakeroot" FAKEROOT
    if [ $? -eq 0 ]; then
        CheckFakerootVersion $FAKEROOT
        if [ $? -eq 0 ]; then
            echo "Using fakeroot $FAKEROOT ..."
            $FAKEROOT $0 $*
            exit $?
        fi
    fi
else
    echo $*
fi

echo "Target: $TARGET"

if [ -z "$STAGING_DIR" ]; then
    echo "Staging dir (-d) not set"
    exit 1
fi
echo "Input: $STAGING_DIR"

if [ -z "$OUTPUT_DIR" ]; then
    echo "Output dir (-o) not set"
    exit 1
fi
echo "Output: $OUTPUT_DIR"

echo "Version: $VERSION"

StripExeAndLibs() {
    if [ "$STRIP_STAGING_TREE" == "yes" ]; then
        STRIP=${TOOLCHAIN_DIR}/${TOOLCHAIN_PREFIX}strip
        test -x $STRIP || (echo "Executable ${TOOLCHAIN_PREFIX}strip is missing"; false)
        CheckRet

        for file in `find $STAGING_DIR -type f`; do
            file ${file} | grep "ELF .* not stripped" >/dev/null
            test $? -eq 0 && ${STRIP} ${file} && echo "Stripping $file"
        done
    fi
}

GenerateUbinizeCfg() {
    IMAGE_PATH=$1
    UBINIZE_CFG_PATH=$2

    rm -f $UBINIZE_CFG_PATH
    touch $UBINIZE_CFG_PATH
    echo "[legato-volume]" >> $UBINIZE_CFG_PATH
    echo "mode=ubi" >> $UBINIZE_CFG_PATH
    echo "image=$IMAGE_PATH" >> $UBINIZE_CFG_PATH
    echo "vol_id=0" >> $UBINIZE_CFG_PATH
    echo "vol_type=dynamic" >> $UBINIZE_CFG_PATH
    echo "vol_name=legato" >> $UBINIZE_CFG_PATH
    echo "vol_flags=autoresize" >> $UBINIZE_CFG_PATH
}

CreateImgFs() {
    local img_type=${1:-yaffs2}
    local ubi_img_type=${2:-squashfs}

    echo "$TARGET: Generating the framework image ($img_type)"

    if [ -z "$TOOLCHAIN_DIR" ]; then
        echo "Unable to find toolchain"
        exit 1
    fi

    local legato_img="$OUTPUT_DIR/legato.$img_type"
    if [[ "$img_type" == "ubi" ]]; then
        legato_img="$OUTPUT_DIR/legato.$ubi_img_type.$img_type"
    fi

    local temp_dir="$OUTPUT_DIR/legatoimg/$img_type"
    mkdir -p $temp_dir

    cd $temp_dir

    case $img_type in
        yaffs2)
            FindTool "mkyaffs2image" MKYAFFS2
            CheckRet

            $MKYAFFS2 -c $PAGE_SIZE -s $OOB_SIZE "$STAGING_DIR" "$legato_img" > yaffs2.log
            CheckRet
            ;;

        ubifs)
            FindTool "mkfs.ubifs" MKUBIFS
            if [ $? -ne 0 ]; then
                echo "Warning: Unable to produce ubifs image: mkfs.ubifs needed"
                return 1
            fi

            $MKUBIFS -r "$STAGING_DIR" -o "$legato_img" -m $PAGE_SIZE -e $LAB_SIZE -c $MAX_LEB_COUNT -F > ubifs.log
            $MKSQUASHFS "$STAGING_DIR" "$legato_img" -noappend -all-root > squashfs.log
            CheckRet
            ;;

        squashfs)
            FindTool "mksquashfs" MKSQUASHFS
            if [ $? -ne 0 ]; then
                echo "Warning: Unable to produce squashfs image: mksquashfs needed"
                return 1
            fi

            $MKSQUASHFS "$STAGING_DIR" "$legato_img" -noappend -all-root > squashfs.log
            CheckRet
            ;;

        ubi)
            CreateImgFs ${ubi_img_type}

            FindTool "ubinize" UBINIZE
            if [ $? -ne 0 ]; then
                echo "Warning: Unable to produce ubi image: ubinize needed"
                return 1
            fi

            GenerateUbinizeCfg $LEGATO_IMG ${temp_dir}/ubinize.cfg

            $UBINIZE -o $legato_img -m $PAGE_SIZE -p $PEB_SIZE -s $PAGE_SIZE ${temp_dir}/ubinize.cfg > ubinize.log
            CheckRet
            ;;

        *)
            echo "Unknown image type '$img_type'"
            exit 1
            ;;
    esac

    export LEGATO_IMG=$legato_img
}

GenerateCwe() {
    img_path=$1
    cwe_suffix=${2:-yaffs2}

    echo "$TARGET: Generating the framework cwe"

    if ! [ -f ${img_path} ] ; then
        echo "$TARGET: $img_path does not exist"
        exit 1
    fi

    FindTool "hdrcnv" HDRCNV
    CheckRet

    FindTool "cwezip" CWEZIP
    CheckRet

    local temp_dir="$OUTPUT_DIR/legatoimg/$cwe_suffix"
    mkdir -p $temp_dir

    cd $temp_dir

    local tmpmbn=$temp_dir/temp.mbn
    if [ -f ${tmpmbn}.hdr ] ; then rm -f ${tmpmbn}.hdr; fi
    if [ -f ${tmpmbn}.cwe ] ; then rm -f ${tmpmbn}.cwe; fi
    if [ -f ${tmpmbn}.cwe.z ] ; then rm -f ${tmpmbn}.cwe.z; fi
    if [ -f legato.cwe ] ; then rm -f legato.cwe; fi
    if [ -f legato.hdr ] ; then rm -f legato.hdr; fi
    if [ -f legatoz.cwe ] ; then rm -f legatoz.cwe; fi
    if [ -f legatoz.hdr ] ; then rm -f legatoz.hdr; fi

    $HDRCNV ${img_path} -OH ${tmpmbn}.hdr -IT USER -PT $PLATFORM -V "$VERSION" -B $COMPAT_BYTE > hdrcnv-tmp.log
    CheckRet

    cat ${tmpmbn}.hdr ${img_path} > ${tmpmbn}.cwe
    CheckRet

    # legato.cwe
    $HDRCNV ${tmpmbn}.cwe -OH legato.hdr -IT APPL -PT $PID -V "$VERSION" -B $COMPAT_BYTE > hdrcnv-legato.log
    CheckRet

    cat legato.hdr ${tmpmbn}.cwe > $OUTPUT_DIR/legato-${cwe_suffix}.cwe
    CheckRet

    # legatoz.cwe
    if $SUPPORT_COMPRESSION; then
        $CWEZIP ${tmpmbn}.cwe -c -o ${tmpmbn}.cwe.z > cwezip.log
        CheckRet

        $HDRCNV ${tmpmbn}.cwe.z -OH legatoz.hdr -IT APPL -PT $PID -V "$VERSION" -B $COMPAT_BYTE > hdrcnv-legatoz.log
        CheckRet

        cat legatoz.hdr ${tmpmbn}.cwe.z > $OUTPUT_DIR/legatoz-${cwe_suffix}.cwe
        CheckRet
    fi
}

CreateImg_mdm9x15() {
    local img_type=${1:-yaffs2}
    local ubi_img_type=${2:-squashfs}

    PAGE_SIZE=4096
    OOB_SIZE=160
    PEB_SIZE=256KiB
    COMPAT_BYTE=00000001
    PLATFORM=9X15
    SUPPORT_COMPRESSION=true

    case $TARGET in
        ar7|ar86)
            PID='A911'
            ;;
        wp85|wp750x)
            PID='Y912'
            PAGE_SIZE=2048
            OOB_SIZE=64
            PEB_SIZE=128KiB
            ;;
        *)
            echo "Unknown product '$TARGET'"
            exit 1
            ;;
    esac

    local cwe_suffix=$img_type
    if [[ "$img_type" == "ubi" ]]; then
        cwe_suffix="${ubi_img_type}.${img_type}"
    fi

    CreateImgFs $img_type $ubi_img_type
    GenerateCwe $LEGATO_IMG $cwe_suffix
}

CreateImg_mdm9x28() {
    local img_type=${1:-ubi}
    local ubi_img_type=${2:-squashfs}

    PAGE_SIZE=4096
    OOB_SIZE=224
    PEB_SIZE=256KiB
    COMPAT_BYTE=00000001
    PID='9X28'
    PLATFORM=$PID
    SUPPORT_COMPRESSION=false

    local cwe_suffix=$img_type
    if [[ "$img_type" == "ubi" ]]; then
        cwe_suffix="${ubi_img_type}.${img_type}"
    fi

    CreateImgFs $img_type $ubi_img_type
    GenerateCwe $LEGATO_IMG $cwe_suffix
}

CreateImg_mdm9x40() {
    local img_type=${1:-ubi}
    local ubi_img_type=${2:-squashfs}

    PAGE_SIZE=4096
    OOB_SIZE=224
    PEB_SIZE=256KiB
    COMPAT_BYTE=00000001
    PID='9X40'
    PLATFORM=$PID
    SUPPORT_COMPRESSION=false

    local cwe_suffix=$img_type
    if [[ "$img_type" == "ubi" ]]; then
        cwe_suffix="${ubi_img_type}.${img_type}"
    fi

    CreateImgFs $img_type $ubi_img_type
    GenerateCwe $LEGATO_IMG $cwe_suffix
}

DefaultImg() {
    local cwe_suffix=${1:-yaffs2}

    ln -sf legato.${cwe_suffix} $OUTPUT_DIR/legato.default

    if [ -e "$OUTPUT_DIR/legato-${cwe_suffix}.cwe" ]; then
        ln -sf legato-${cwe_suffix}.cwe $OUTPUT_DIR/legato.cwe
    fi

    if [ -e "$OUTPUT_DIR/legatoz-${cwe_suffix}.cwe" ]; then
        ln -sf legatoz-${cwe_suffix}.cwe $OUTPUT_DIR/legatoz.cwe
    fi
}

StripExeAndLibs

case $TARGET in
    ar7 | ar86)
        CreateImg_mdm9x15 yaffs2
        DefaultImg yaffs2
        ;;
    wp750x | wp85)
        CreateImg_mdm9x15 yaffs2
        CreateImg_mdm9x15 ubi squashfs
        DefaultImg "squashfs.ubi"
        ;;
    ar758x | wp76xx)
        CreateImg_mdm9x28 ubi squashfs
        DefaultImg "squashfs.ubi"
        ;;
    ar759x)
        CreateImg_mdm9x40 yaffs2
        CreateImg_mdm9x40 ubi squashfs
        DefaultImg "squashfs.ubi"
        ;;
    raspi)
        CreateImgFs squashfs
        ;;
    ?)
        echo "$0: nothing to do for target $TARGET"
        ;;
esac

exit 0
