#!/bin/bash

copyright="
Copyright (C) Sierra Wireless Inc.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="create Legato system tree in read-only"

help_usage=(
"[TARGET]"
)

help_long_description=(
"Create Legato system tree in read-only for a target"
)

CheckForHelp $@

target=$1
test -z "$target" && target=ar759x

# Remove older read-only staging tree
rm -rf build/$target/readOnlyStaging

# Make the read-only staging tree structure
mkdir -p build/$target/readOnlyStaging/legato/systems/current
mkdir -p build/$target/readOnlyStaging/legato/smack

# Add a file 'read-only' to mark the staging tree as read-only
# This is used in supervisor and config tree to perform some specific
# actions
touch build/$target/readOnlyStaging/legato/systems/current/read-only

# Copy the staging tree into the read-only
cp -a build/$target/staging/system/. build/$target/readOnlyStaging/legato/systems/current/

# Mark the system 0 as good
echo -n "good" >build/$target/readOnlyStaging/legato/systems/current/status
echo -n "0" >build/$target/readOnlyStaging/legato/systems/current/index

# Copy the start script and apps stuff into the read-only tree
cp -a build/$target/staging/start build/$target/staging/apps/ build/$target/readOnlyStaging/legato/

# Build the final config-tree for
sysConfigFile=build/$target/readOnlyStaging/legato/systems/current/config/system.scissors
appsConfigFile=build/$target/readOnlyStaging/legato/systems/current/config/apps.cfg
usersConfigFile=build/$target/readOnlyStaging/legato/systems/current/config/users.cfg
modsConfigFile=build/$target/readOnlyStaging/legato/systems/current/config/modules.cfg

# Construct the system config tree from the users.cfg and apps.cfg files.
echo '{ "users" ' > $sysConfigFile
cat $usersConfigFile >> $sysConfigFile
echo ' "apps" ' >> $sysConfigFile
cat $appsConfigFile >> $sysConfigFile
echo ' "modules" ' >> $sysConfigFile
cat $modsConfigFile >> $sysConfigFile
echo ' }' >> $sysConfigFile

# Remove the users.cfg apps.cfg and modules.cfg files so the Update Daemon won't
# waste time importing them at boot time.
rm $appsConfigFile $usersConfigFile $modsConfigFile

# Make the directory and deploy the apps
mkdir build/$target/readOnlyStaging/legato/systems/current/appsWriteable
cd build/$target/readOnlyStaging/legato/systems/current/appsWriteable

# Make the bin and lib directory
for f in ../apps/*; do mkdir `basename $f` `basename $f`/bin `basename $f`/lib; done

# Perform some move of file and make useful links
for f in *; do ln=`ls -l ../apps/$f | sed 's,^.*/legato/,,'`; echo $f $ln;
   for d in bin lib; do
      for ff in ../../../../../readOnlyStaging/legato/$ln/read-only/$d/*; do
         mv $ff `basename $f`/$d/.
         ln -s /legato/systems/current/appsWriteable/`basename $f`/$d/`basename $ff` \
               ../../../../../readOnlyStaging/legato/$ln/read-only/$d/`basename $ff`
      done
   done
   # Deploy read-only tree for an apps if it exists
   if [ -d ../../../../../readOnlyStaging/legato/$ln/read-only/usr ]; then
     mkdir -p `basename $f`/usr/
     for dd in `cd ../../../../../readOnlyStaging/legato/$ln/read-only/usr; find -type d`; do
        mkdir -p `basename $f`/usr/$dd
        for ff in ../../../../../readOnlyStaging/legato/$ln/read-only/usr/$dd/*; do
           [ -f $ff ] &&
              mv $ff `basename $f`/usr/$dd/. &&
              ln -s /legato/systems/current/appsWriteable/`basename $f`/usr/$dd/`basename $ff` \
                    ../../../../../readOnlyStaging/legato/$ln/read-only/usr/$dd/`basename $ff`
        done
     done
   fi
   # Deploy writeable tree for an apps if it exists
   if [ -d ../../../../../readOnlyStaging/legato/$ln/writeable ]; then
     for dd in `cd ../../../../../readOnlyStaging/legato/$ln/writeable; find -type d`; do
        mkdir -p `basename $f`/$dd
        for ff in ../../../../../readOnlyStaging/legato/$ln/writeable/$dd/*; do
           [ -f $ff ] &&
              mv $ff `basename $f`/$dd/. &&
              ln -s /legato/systems/current/appsWriteable/`basename $f`/$dd/`basename $ff` \
                    ../../../../../readOnlyStaging/legato/$ln/writeable/$dd/`basename $ff`
        done
     done
   fi
done

# Add some directory and links for powerMgr tools
mkdir -p powerMgr/sys/power
ln -s /sys/power/wake_lock powerMgr/sys/power
ln -s /sys/power/wake_unlock powerMgr/sys/power

exit 0
