#!/bin/bash

function PrintUsage()
{
    echo "USAGE: $(basename $0) APP_NAME DEST_IP"
    echo
    echo "  where, APP_NAME = the application to be removed.  E.g., 'myApp'."
    echo
    echo "         DEST_IP = the IP address of the target device."
    echo
}

APP_NAME=$1
DEST_IP=$2

# Check if they are asking for help.
if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
then
    PrintUsage
    exit 0
fi

# Check that the app name argument was provided.
if ! [ "$APP_NAME" ]
then
    echo "***ERROR: First argument should be an application name."
    PrintUsage
    exit 1
fi

# Check that the second argument is provided and can be pinged.
if ! [ $DEST_IP ]
then
    echo "***ERROR: Second argument should be an IP address."
    PrintUsage
    exit 1
fi

if ! ping -c 1 -w 1 $DEST_IP > /dev/null
then
    echo "***ERROR: Device address $DEST_IP seems to be unreachable."
    exit 1
fi

# Tell the device to stop the application and uninstall it.
APP_NAME=$(basename "$APP_NAME" | sed 's/\.[^.]*$//')
ssh root@$DEST_IP "/usr/local/bin/app remove $APP_NAME"
