#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="remove app from target"

help_usage=(
"APP_NAME [TARGET_IP]"
)

help_long_description=(
"Remove the app given by APP_NAME from the IP address of the target, TARGET_IP"
"If APP_NAME is given as \"*\" (including the quotes) then remove all apps"
)

CheckForHelp $@
APP_NAME=$1

# Check that the app name argument was provided.
if ! [ "$APP_NAME" ]
then
    ExitWithError "First argument should be an application name."
fi

# Check that the second argument is provided and can be pinged.
SetTargetIP $2

# Tell the device to stop the application and uninstall it.
APP_NAME=$(basename "$APP_NAME" | sed 's/\.[^.]*$//')
SshToTarget "$BIN_PATH/app remove '$APP_NAME'"
