#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="Encrypts the application package"

help_usage=(
"APP_FILE"
)

help_long_description=(
"This tool encrypts a given application package. The default security-pack"
"script renames the received file without encrypting it. Customers have to"
"rewrite this script as per their requirement. Secure installation also"
"requires a corresponding security-unpack tool on the device to decrypt the"
"received image."
)

CheckForHelp $@

# Here, do nothing but rename the file what it receive.
cp "$1" "$1.sec"
