#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="set the time on target"

help_usage=(
"[TARGET_IP]"
)

help_long_description=(
"Sets the target time to be the same as the host time."
"The time is synchronized on the basis of UTC time but the time displayed"
"by date or the time stamps in syslog will use timezone information"
"if set by settz."
)

help_notes=(
"This tool creates a master ssh socket named root@<TARGET_IP>_legato_tools"
"in .ssh/ so that it can open subsequent connections quickly."
"The socket is deleted if the script ends normally."
)

CheckForHelp $@

SetTargetIP $1
StartFastSsh
FastSsh root@$TARGET_IP "date -u $(date -u +\"%m%d%H%M%Y.%S\")"
EndFastSsh
