#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="show status of apps on target"

help_usage=(
"APP_NAME [TARGET_IP]"
)

help_long_description=(
"If the application APP_NAME is installed on the target at"
"TARGET_IP then the app will be started."
"If the APP_NAME is given as \"*\" (including the quotes) then all"
"apps on the target will be started."
)

CheckForHelp $@

APP_NAME=$1
if ! [ "$APP_NAME" ]
then
    ExitWithError "First argument should be an application name."
fi

# Check that the second argument is provided and can be pinged.
SetTargetIP $2

# Tell the device to start the application.
APP_NAME=$(basename "$APP_NAME" | sed 's/\.[^.]*$//')
SshToTarget "/usr/local/bin/app start '$APP_NAME'"

