#!/bin/bash

# This script starts the Legato Service Directory and Log Control Daemon, if they aren't
# already running.  It outputs "Already running." and exits with code 1 if they were already
# running.  It outputs "Started." and exits with code 0 if they were started.  It outputs
# "***ERROR: ", followed by an error message (to standard error) and exits with code 2 if it fails.


LOG_FILE="$1"


function PrintUsage()
{
    echo
    echo "USAGE: $(basename $0) [ LOGFILE ]"
    echo
    echo " where LOGFILE can be used to specify the name of a file to output the legato"
    echo "       log messages to."
    echo
}


if [ $# -gt 1 ]
then
    echo "***ERROR: Too many parameters." 1>&2
    exit 2
fi


if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "help" ]
then
    PrintUsage
    exit 0
fi


if ! [ $LEGATO_ROOT ]
then
    echo "WARNING: LEGATO_ROOT environment variable not set." 1>&2
    echo "         Should be set to the root directory of your Legato framework." 1>&2
    echo "         Assuming '$(pwd)'" 1>&2
    LEGATO_ROOT=$(pwd)
fi

if ! [ $TARGET ]
then
    TARGET=localhost
else
    if [ "$TARGET" != "localhost" ]
    then
        echo "***ERROR: Sorry, target '$TARGET' is not supported yet." 1>&2
        exit 2
    fi
fi


# If the Service Directory isn't already running, start it.
if ! pgrep -f serviceDirectory > /dev/null
then
    if [ "$LOG_FILE" != "" ]
    then
        $LEGATO_ROOT/build/$TARGET/bin/serviceDirectory 2>> "$LOG_FILE" &
    else
        $LEGATO_ROOT/build/$TARGET/bin/serviceDirectory &
    fi

    SERVICE_DIRECTORY_PID=$!

    # Wait for the Service Directory to start.
    sleep 0.2

    if ! kill -0 $SERVICE_DIRECTORY_PID 2> /dev/null
    then
        echo "***ERROR: Failed to start Service Directory." 1>&2
        exit 2
    fi

    STARTED=true
fi


# If the Log Control Daemon isn't already running, start it.
if ! pgrep -f logCtrlDaemon > /dev/null
then
    if [ "$LOG_FILE" != "" ]
    then
        $LEGATO_ROOT/build/$TARGET/bin/logCtrlDaemon 2>> "$LOG_FILE" &
    else
        $LEGATO_ROOT/build/$TARGET/bin/logCtrlDaemon &
    fi

    LOG_CONTROL_DAEMON_PID=$!

    if ! kill -0 $LOG_CONTROL_DAEMON_PID 2> /dev/null
    then
        echo "***ERROR: Failed to start Log Control Daemon." 1>&2
        exit 2
    fi

    # Wait for start-up log spam to empty out.
    sleep 0.2

    STARTED=true
fi

if [ $STARTED ]
then
    echo "Started."
    exit 0
else
    echo "Already running."
    exit 1
fi
