#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

if ! [ $LEGATO_ROOT ]; then echo "Run bin/legs first" >&2; exit 1; fi
. "${LEGATO_ROOT}/framework/tools/scripts/shlib"

help_short_desc="show status of apps on target"

help_usage=(
"[TARGET_IP]"
)

help_long_description=(
"The target at TARGET_IP will be queried to find out the status of all"
"installed applications and a list of all running and stopped apps"
"will be returned"
)

CheckForHelp $@

SetTargetIP $1

# List the contents of the application install directory.
SshToTarget "/usr/local/bin/app status \"*\""

