#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc. Use of this work is subject to license.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="stop an app that is currently running on target"

help_usage=(
"APP_NAME [TARGET_IP]"
)

help_long_description=(
"If APP_NAME is currently running on the target at TARGET_IP, $commandName"
"will cause the app to cease execution. If APP_NAME is not currently running"
"or is not installed, a message to that effect will be printed."
"If the APP_NAME is given as \"*\" (including the quotes) then all"
"apps on the target will be stopped."
)

CheckForHelp $@

APP_NAME=$1
if ! [ "$APP_NAME" ]
then
    ExitWithError "First argument should be an application name."
fi

SetTargetIP $2

# Tell the device to stop the application.
APP_NAME=$(basename "$APP_NAME" | sed 's/\.[^.]*$//')
SshToTarget "/usr/local/bin/app stop '$APP_NAME'"
