#!/bin/bash

function PrintUsage()
{
    echo "USAGE: $(basename $0) APP_NAME DEST_IP"
    echo
    echo "  where, APP_NAME = the application to be removed.  E.g., 'myApp'."
    echo "  If APP_NAME = \"*\" that means all apps."
    echo
    echo "  DEST_IP = the IP address of the target device.  If DEST_IP is an available"
    echo "  environment variable it does not need to be passed in the command-line."
    echo
}

APP_NAME=$1
TARGET_IP=$2

# Check if they are asking for help.
if [ "$1" = "-h" -o "$1" = "help" -o "$1" = "--help" ]
then
    PrintUsage
    exit 0
fi

# Check that the app name argument was provided.
if ! [ "$APP_NAME" ]
then
    echo "***ERROR: First argument should be an application name."
    PrintUsage
    exit 1
fi

# Check that the second argument is provided and can be pinged.
if ! [ $TARGET_IP ]
then
    if ! [ $DEST_IP ]
    then
        echo "***ERROR: Destination IP address not available."
        PrintUsage
        exit 1
    fi

    TARGET_IP=$DEST_IP
fi

if ! ping -c 1 -w 1 $TARGET_IP > /dev/null
then
    echo "***ERROR: Device address $TARGET_IP seems to be unreachable."
    exit 1
fi

# Tell the device to stop the application.
APP_NAME=$(basename "$APP_NAME" | sed 's/\.[^.]*$//')
ssh root@$TARGET_IP "/usr/local/bin/app stop '$APP_NAME'"
