#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="Create Legato cwe image from legato system file"

help_usage=(
"TARGET SYSTEM_FILE [OUTPUT_DIR]"
"-h"
"--help"
)

help_long_description=(
"Generates a cwe image from legato system file."
""
"$commandName TARGET SYSTEM_FILE [OUTPUT_DIR]"
"  - Create cwe image from system update file. Output will be generated in OUTPUT_DIR if specified."
"    Otherwise, output will be placed in current directory."
""
"$commandName -h"
"$commandName --help"
"  - Print this help text."
""
"For ar7/ar86/wp85/wp750x targets:"
""
"   This creates a partition that you can use with fwupdate or airvantage"
"   to update the legato within your target."
""
"Examples:"
""
"   # Generate cwe image from system.wp85.update and place output in current directory"
"   $(basename "$0") wp85 system.wp85.update"
""
"   # Generate cwe image from system.wp85.update and place output in build_system"
"   $(basename "$0") wp85 system.wp85.update build_system"
)

CheckForHelp $@

if ! type mklegatoimg > /dev/null 2>&1; then
    ExitWithError "Failed to find mklegatoimg."
fi

if ! type update-util > /dev/null  2>&1; then
    ExitWithError "Failed to find update-util."
fi

if [ -z "$LEGATO_ROOT" ]; then
    ExitWithError "LEGATO_ROOT is not set. Please set it properly."
fi

if [ $# -lt 2 ] || [ $# -gt 3 ]
then
    ExitWithError "Invalid number of arguments."
fi

TARGET=$1
SYSTEM_FILE=$2
OUTPUT_DIR=$3

if [ ! -f "$SYSTEM_FILE" ]
then
    ExitWithError "Bad system file $SYSTEM_FILE"
fi

SYSTEM_NAME=$(basename $SYSTEM_FILE)

if [ -z "$OUTPUT_DIR" ]
then
    echo "Warning: output directory is not provided. Using $PWD as output directory."
    OUTPUT_DIR=$PWD
fi

INTERMEDIATE_DIR="$OUTPUT_DIR"/_staging_$SYSTEM_NAME

if [ ! -d $INTERMEDIATE_DIR ]
then
    mkdir -p "$INTERMEDIATE_DIR"
fi

# Check whether intermediate directory is empty, if not remove everything from it.
if [ -n "$(ls -A $INTERMEDIATE_DIR)" ]
then
    echo "Removing old content of $INTERMEDIATE_DIR"
    rm -rf "$INTERMEDIATE_DIR"/*
fi

case $TARGET in
    ar7 | ar86| wp750x| wp85| ar758x| ar759x)

        echo "Unpacking $SYSTEM_FILE ..."
        update-util "$SYSTEM_FILE" -x -s -p "$INTERMEDIATE_DIR" > /dev/null
        if [ $? -ne 0 ]
        then
            ExitWithError "Failed to unpack $SYSTEM_FILE"
        fi
        echo "Preparing staging directory $INTERMEDIATE_DIR"
        cp $LEGATO_ROOT/targetFiles/shared/bin/start "$INTERMEDIATE_DIR"

        echo "Creating cwe image from directory $INTERMEDIATE_DIR"

        mklegatoimg -t "$TARGET" -d "$INTERMEDIATE_DIR" -o "$OUTPUT_DIR"

        if [ $? -ne 0 ]
        then
            ExitWithError "Failed to create cwe image"
        fi
        ;;
    ?)
        echo "$0: nothing to do for target $TARGET"
        ;;
esac

exit 0
