#!/bin/bash
copyright="
Copyright (C) Sierra Wireless Inc.
"

. "$(dirname "${BASH_SOURCE[0]}")/shlib"

help_short_desc="apply update to target device"

help_usage=(
"UPDATE_FILE [DEST_IP]"
)

help_long_description=(
"Apply the given update pack to the target device at a given IP address."
""
"UPDATE_FILE is the update pack file to be applied."
"E.g., 'myApp.ar7.update' or 'system.wp85.update'."
""
"DEST_IP is the IP address of the target device. If DEST_IP is not specified on"
"the command line, the contents of the DEST_IP environment variable will be used."
""
"System update files are created by 'mksys'."
"App update files are created by 'mkapp'."
"App removal update packs and firmware update packs can be created using 'update-pack'."
)

CheckForHelp $@
UPDATE_FILE=$1

# Check that the first argument exists and is a file.
if ! [ -f "$UPDATE_FILE" ]
then
    ExitWithError "First argument should be an update pack file."
fi

# Check that the second argument is provided and can be pinged.
SetTargetIP $2

# Pipe the update pack to the on-target "update" program through ssh.
echo "Applying update from file '$UPDATE_FILE' to device at address '$TARGET_IP'."
cat $UPDATE_FILE | SshToTarget "/legato/systems/current/bin/update"

result=$?
if [ "$result" = 0 ]; then
    echo "Done"
else
    echo "Update failed"
    SshToTarget "/legato/systems/current/bin/legato status"
    exit $result
fi
