/** @file cdata.c
 *
 * Implement component instance data functions.  This is a wrapper around thread
 * local storage where each thread has an active instance of each component.  Requesting
 * a component instance's data will get the component's active instance from TLS.  This is
 * used by the LE_CDATA_THIS macro to get the active instance's component data for the file.
 */

#include "legato.h"
#include "thread.h"

//--------------------------------------------------------------------------------------------------
/**
 * Get this component instance.
 *
 * @note This should typically not be used by a user application; use LE_CDATA_THIS instead.
 */
//--------------------------------------------------------------------------------------------------
unsigned int le_cdata_GetInstance
(
    unsigned int componentKey  ///< Key identifying the component.  This is automatically
                               ///< generated by mkTools.
)
{
     const cdata_ThreadRec_t* cdataPtr = thread_GetCDataInstancePtr();
     int i;

     LE_FATAL_IF(NULL == cdataPtr, "No component instances defined for this task");

     for (i = 0; cdataPtr[i].key >= 0; ++i)
     {
         if ((unsigned int) cdataPtr[i].key == componentKey)
         {
             return cdataPtr[i].instance;
         }
     }

     LE_FATAL("Component with key %d does not exist in this task (in %p)\n",
              componentKey, cdataPtr);
}
