#!/bin/bash
#*******************************************************************************
# Copyright (c) 2012 Sierra Wireless and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# and Eclipse Distribution License v1.0 which accompany this distribution.
#
# The Eclipse Public License is available at
#   http://www.eclipse.org/legal/epl-v10.html
# The Eclipse Distribution License is available at
#   http://www.eclipse.org/org/documents/edl-v10.php
#
# Contributors:
#     Guilhem Saurel for Sierra Wireless - initial script
#*******************************************************************************

rm /opt/mihini/{apps,persist,update}
rm -rf /opt/mihini /etc/systemd/system/mihini.service /etc/ld.so.conf.d/01-mihini.conf

chown -R root:root /var/opt/mihini
userdel mihini || echo "userdel mihini failed"
ldconfig
