#!/bin/sh

# Configures file system access permissions for modem and positioning services.
# TODO: Change to use group-based permissions and/or mandatory access control.

# This is the main QMI access mechanism.
chmod o+rw /var/qmux_connect_socket

# We know for sure that the QMI clients try to use these from time-to-time:
chmod o+rw /dev/diag
chmod o+rw /dev/smem_log

# These may or may not be used, but appear modem related.  TODO: Confirm.
chmod o+rw /dev/apr_apps2
chmod o+rw /dev/msm_*
chmod o+rw /dev/nmea
chmod o+rw /dev/qmi0
chmod o+rw /dev/qmi1
chmod o+rw /dev/qmi2
chmod o+rw /dev/smd*
chmod o+rw /dev/ramdump_*
chmod o+rw /dev/sierra_*
chmod o+rw /dev/snd/*
chmod o+rw /dev/ccid_*
