#!/bin/sh

# Make /home actually be /mnt/flash/home (and make sure /home/root exists).
echo "Remapping /home --> /mnt/flash/home"
mkdir -p /mnt/flash/home/root
mount --bind /mnt/flash/home        /home

# Make /usr/local actually be /mnt/flash/usr/local.
echo "Remapping /usr/local --> /mnt/flash/usr/local"
mkdir -p /mnt/flash/usr/local
mkdir -p /usr/local
mount --bind /mnt/flash/usr/local   /usr/local

# Make /opt actually be /mnt/flash/opt.
echo "Remapping /opt --> /mnt/flash/opt"
mkdir -p /mnt/flash/opt
mkdir -p /opt
mount --bind /mnt/flash/opt /opt

# Make certain files in /etc/ writeable but not persistent (changes will be lost on reboot).
# We do this by copying these files from /etc into /var/run (RAM file system) and bind mounting
# them back into /etc.
for filename in ld.so.conf profile
do
    echo "Remapping /etc/$filename --> /var/run/$filename"
    cp /etc/$filename /var/run/
    mount --bind /var/run/$filename /etc/$filename
done

# Make certain files in /etc writeable and persistent.
# Because the root file system is supposed to be read-only (to allow resetting back to factory
# settings), we create a writeable copy of these files in /mnt/flash/etc and bind-mount them
# back into /etc.
mkdir -p /mnt/flash/etc
for filename in passwd group
do
    # If the file already exists in /mnt/flash/etc, don't overwrite it with the defaults from
    # the root fs.
    if ! [ -e /mnt/flash/etc/$filename ]
    then
        echo "Copying /etc/$filename --> /mnt/flash/etc/$filename"
        cp /etc/$filename /mnt/flash/etc/
    fi
    echo "Remapping /etc/$filename --> /mnt/flash/etc/$filename"
    mount --bind /mnt/flash/etc/$filename /etc/$filename
done


# Add /usr/local/bin to PATH in /etc/profile
echo "Adding /usr/local/bin to PATH."
echo 'export PATH=/usr/local/bin:$PATH' >> /etc/profile

# Add /usr/local/lib to the system's library search path, if it isn't already there.
if ! grep '/usr/local/lib' /etc/ld.so.conf > /dev/null
then
    echo "Adding /usr/local/lib to the system library search path."
    echo '/usr/local/lib' >> /etc/ld.so.conf
fi

# Update the ld library search cache.
# NOTE: The rootfs, including /etc will be read-only, so we have to actually create
# a library search cache file somewhere else and then bind-mount it back into /etc/ld.so.cache
# so that ld can find it when it needs it.
echo "Updating the the library search cache."
ldconfig -v -C /var/run/ld.so.cache
mount --bind /var/run/ld.so.cache /etc/ld.so.cache
