#!/bin/sh

# Set the SMACK label for /dev/null and /dev/zero to "*" so that any everyone can have access to them.
/usr/local/bin/xattr set security.SMACK64 "*" /dev/null
/usr/local/bin/xattr set security.SMACK64 "*" /dev/zero

# TODO: This section of code should be done earlier in the boot sequence so that syslogd will start
# earlier with the proper label.  Leaving it here for now until we have a hook into earlier stages
# of the boot system.  Another option is for Legato to build a log forwarding daemon that has the
# proper permissions.  In that case this code is not needed at all.

# Only allow the "framework" labeel to access the Legato directory.
mkdir -p /opt/legato
/usr/local/bin/xattr set security.SMACK64 "framework" /opt/legato

# Set security.SMACK64EXEC label to fg_10_StartLegato so that it can set the smack label for the
# supervisor and installer.
/usr/local/bin/xattr set security.SMACK64EXEC "admin" /mnt/flash/startup/fg_10_StartLegato

# Set the syslogd restart script to run as label "syslog" so that when it starts syslogd, syslogd
# will run with the "syslog" label as well.  Can't just set the security.SMACK64EXEC label of syslogd
# because busybox syslogd is part of one large busybox utils file.
/usr/local/bin/xattr set security.SMACK64EXEC "syslog" /mnt/flash/startup/fg_02_RestartSyslogd

# Give subjects with "_", "admin" and "framework" rw access to "syslog".
echo "_ syslog rw---" > /opt/legato/smack/load
echo "admin syslog rw---" >/opt/legato/smack/load
echo "framework syslog rw---" > /opt/legato/smack/load
