#!/bin/sh

EXEC=$(basename $0)

# Prepend the PATH with paths for the devMode, and take out the default PATH for the stub.
export PATH="/legato/systems/current/appsWriteable/devMode/bin/:/legato/systems/current/appsWriteable/devMode/sbin/:$(echo $PATH | sed 's#/legato/systems/current/bin:##g')"

CANDIDATE=$(which $EXEC 2>/dev/null)
if [ -z "$CANDIDATE" ]; then
    echo "'$EXEC' could not be executed." >&2
    echo
    if /legato/systems/current/bin/app status devMode | grep -q "not installed"; then
        echo "It is provided by the 'devMode' app, which is not installed." >&2
        echo "Please install it as to be able to debug your system." >&2
        echo "More information available at https://docs.legato.io/latest/basicTargetDevMode.html ." >&2
    else
        echo "It is not shipped with your current version of the 'devMode' app." >&2
    fi

    exit 1
fi

exec $CANDIDATE "$@"
