#
# Init file for reports generated by ifgen
#
# Copyright (C) Sierra Wireless Inc.
#

import codeGenHelpers, interfaceIR

def AddLangArgumentGroup(parser):
    pass

Filters = { 'MessageSize':          codeGenHelpers.GetMessageSize,
            'LocalMessageSize':     codeGenHelpers.GetLocalMessageSize, }
Tests = { 'HandlerType':            lambda obj: isinstance(obj, interfaceIR.HandlerType)}
Globals = { }

GeneratedFiles = { 'mem-report': '%s_mem_report.html' }
