#! /bin/sh

LEGATO_SYSTEM_PATH="/legato/systems/current/bin"

# If PATH doesn't contain LEGATO_SYTEM_PATH, add it.
if [ ${PATH/$LEGATO_SYSTEM_PATH} = $PATH ]; then
    export PATH=/legato/systems/current/bin:$PATH
fi

case "$1" in

    stop)
        # if legato isn't running legato script likely won't be found as current/bin
        # won't be set.
        if [ -d $LEGATO_SYSTEM_PATH ]; then
            legato stop
        else
            echo "Called stop but legato doesn't seem to be running."
        fi
    ;;

    "")
        cd /mnt/legato
        ./system/bin/startSystem &
    ;;

esac

