#!/bin/bash

TARGET_ADDR=$1
ORIG_DIR=$PWD
SCRIPT_DIR=$(readlink -f $(dirname ${BASH_SOURCE[0]}))

function RunTest()
{
    TEST_FILE_DIR=$(dirname $1)
    TEST_FILE_NAME=$(basename $1)

    # Go to the directory of the test file.
    cd $SCRIPT_DIR/$TEST_FILE_DIR

    # Run the test.
    ./$TEST_FILE_NAME $TARGET_ADDR

    # Check the return code.
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        echo -e $COLOR_ERROR "Test '$TEST_FILE_NAME' Failed!" $COLOR_RESET
        exit $RETVAL
    fi
}

# Run tests.  All tests should take the target's IP address as the first parameter.
RunTest framework/supervisor/supervisorTest.sh
RunTest framework/watchdog/watchdogTest.sh
RunTest framework/configTree/configTargetTests.sh
RunTest framework/updateTool/updateToolTest.sh
RunTest framework/smackAPI/smackApiTest.sh
RunTest framework/smack/smackTest.sh
RunTest framework/sandboxLimits/limitsTest.sh

# Clear out the any test apps, and clean up after any non-sandboxed ones.
rmapp \* "$TARGET_ADDR"
ssh root@$AR7_IP_ADDR "rm -rf \`find /mnt/flash/home/* -type d | grep app\`"

cd $ORIG_DIR
