/**
 * @file configuration.h
 *
 * This file has been automatically generated by libcbor build.
 * It is saved for RTOS builds because libcbor is not built as library on rtos.
 *
 * Copyright (C) Sierra Wireless Inc.
 */
#ifndef LIBCBOR_CONFIGURATION_H
#define LIBCBOR_CONFIGURATION_H

#define CBOR_MAJOR_VERSION 0
#define CBOR_MINOR_VERSION 7
#define CBOR_PATCH_VERSION 0

#define CBOR_CUSTOM_ALLOC 0
#define CBOR_BUFFER_GROWTH 2
#define CBOR_MAX_STACK_SIZE 2048
#define CBOR_PRETTY_PRINTER 1

#define CBOR_RESTRICT_SPECIFIER restrict
#define CBOR_INLINE_SPECIFIER

#endif //LIBCBOR_CONFIGURATION_H
