#!/bin/sh

# Starts up the Legato runtime environment.

mkdir -p /opt/legato/apps

# Set the Legato supervisor and installer to run as label "admin".
/usr/local/bin/xattr set security.SMACK64EXEC admin /usr/local/bin/supervisor
/usr/local/bin/xattr set security.SMACK64EXEC admin /usr/local/bin/appSetFilePermissions

/usr/local/bin/legato start
