{#-
 #  Jinja2 template for generating service defines for Legato APIs.
 #
 #  Note: C/C++ comments apply to the generated code.  For example this template itself is not
 #  autogenerated, but the comment is copied verbatim into the generated file when the template is
 #  expanded.
 #
 #  Copyright (C) Sierra Wireless Inc.
 #}
/*
 * ====================== WARNING ======================
 *
 * THE CONTENTS OF THIS FILE HAVE BEEN AUTO-GENERATED.
 * DO NOT MODIFY IN ANY WAY.
 *
 * ====================== WARNING ======================
 */


#ifndef {{apiName|upper}}_SERVICE_H_INCLUDE_GUARD
#define {{apiName|upper}}_SERVICE_H_INCLUDE_GUARD


#include "legato.h"

#define PROTOCOL_ID_STR IFGEN_{{apiBaseName|upper}}_PROTOCOL_ID

{%- if args.localService %}
#define SERVICE_INSTANCE_NAME "{{serviceName}}"
{%- else %}
#ifdef MK_TOOLS_BUILD
    extern const char** {{apiName}}_ServiceInstanceNamePtr;
    #define SERVICE_INSTANCE_NAME (*{{apiName}}_ServiceInstanceNamePtr)
#else
    #define SERVICE_INSTANCE_NAME "{{serviceName}}"
#endif
{%- endif %}

#endif // {{apiName|upper}}_SERVICE_H_INCLUDE_GUARD
