{#-
 #  Jinja2 template for generating message defines for Legato APIs.
 #
 #  Note: C/C++ comments apply to the generated code.  For example this template itself is not
 #  autogenerated, but the comment is copied verbatim into the generated file when the template is
 #  expanded.
 #
 #  Copyright (C) Sierra Wireless Inc.
 #}
/*
 * ====================== WARNING ======================
 *
 * THE CONTENTS OF THIS FILE HAVE BEEN AUTO-GENERATED.
 * DO NOT MODIFY IN ANY WAY.
 *
 * ====================== WARNING ======================
 */


#ifndef {{apiName|upper}}_MESSAGES_H_INCLUDE_GUARD
#define {{apiName|upper}}_MESSAGES_H_INCLUDE_GUARD


#include "legato.h"

#define PROTOCOL_ID_STR "{{idString}}"

#ifdef MK_TOOLS_BUILD
    extern const char** {{apiName}}_ServiceInstanceNamePtr;
    #define SERVICE_INSTANCE_NAME (*{{apiName}}_ServiceInstanceNamePtr)
#else
    #define SERVICE_INSTANCE_NAME "{{serviceName}}"
#endif


#define _MAX_MSG_SIZE {{messageSize}}

// Define the message type for communicating between client and server
typedef struct __attribute__((packed))
{
    uint32_t id;
    uint8_t buffer[_MAX_MSG_SIZE];
}
_Message_t;
{% for function in functions %}
#define _MSGID_{{apiName}}_{{function.name}} {{loop.index0}}
{%- endfor %}


#endif // {{apiName|upper}}_MESSAGES_H_INCLUDE_GUARD
