//--------------------------------------------------------------------------------------------------
/**
 * @page mkTools_NinjaScriptGenerator Ninja Script Generator
 *
 * There are various ninja build scripts that get generated by this module.
 *
 * There's a function to generate each type of .ninja for each OS type:
 *
 * - ninja::Generate...(Component_t*) - Stand-alone component library.
 *
 * - ninja::Generate...(Exe_t*) - Executable and associated component libraries.
 *
 * - ninja::Generate...(App_t*) - Application bundle, including executables, component libraries,
 *                                bundled files, a configuration data file,
 *                                and an info.properties file.
 *
 * - ninja::Generate...(System_t*) - System bundle, including all app bundles and user binding
 *                                   configuration.
 *
 * None of the scripts do configuration generation or exe main code generation.  The scripts expect
 * those things to be done before the scripts are run.  The ninja scripts will run ifgen to
 * generate interface code, though.
 *
 * Each script includes a rule to check that none of the definition files that it is generated
 * from have been changed.  If they have, the script will delete itself and run the appropriate
 * mktool to regenerate itself.
 *
 * <hr>
 *
 * Copyright (C) Sierra Wireless Inc.
 */
//--------------------------------------------------------------------------------------------------

#ifndef LEGATO_NINJA_SCRIPT_GENERATOR_H_INCLUDE_GUARD
#define LEGATO_NINJA_SCRIPT_GENERATOR_H_INCLUDE_GUARD

namespace ninja
{


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for a stand-alone component library.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateLinux
(
    model::Component_t* componentPtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for a stand-alone component library.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateRtos
(
    model::Component_t* componentPtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for an executable and associated component and IPC interface
 * libraries.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateLinux
(
    model::Exe_t* exePtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for an executable and associated component and IPC interface
 * libraries.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateRtos
(
    model::Exe_t* exePtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for a Linux application.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateLinux
(
    model::App_t* appPtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for an RTOS application.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateRtos
(
    model::App_t* appPtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for a module.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateLinux
(
    model::Module_t* modulePtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate a build script for a system.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateLinux
(
    model::System_t* systemPtr,
    const mk::BuildParams_t& buildParams
);


//--------------------------------------------------------------------------------------------------
/**
 * Generate build script for a system.
 **/
//--------------------------------------------------------------------------------------------------
void GenerateRtos
(
    model::System_t* systemPtr,
    const mk::BuildParams_t& buildParams
);


} // namespace ninja

#endif // LEGATO_NINJA_SCRIPT_GENERATOR_H_INCLUDE_GUARD
